### ISSUE TITLE
[bug]: No matching key. keychain: ${topic} on disconnect

### ISSUE THREAD

**Issue by bujoralexandru** [WalletConnect/modal-react-native#11]
### Description

https://github.com/WalletConnect/modal-react-native/assets/17970235/f744c148-5700-4fd4-ae79-647164c09f04

### WalletConnect Modal SDK version

1.0.0-rc.2

### Output of `npx react-native info`

```
System:
    OS: macOS 13.4.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 2.34 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.20.0 - ~/.volta/tools/image/node/16.20.0/bin/node
    Yarn: 1.22.19 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
    npm: 8.19.4 - ~/.volta/tools/image/node/16.20.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.12.0 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK:
      API Levels: 23, 26, 28, 29, 30, 31, 32, 33
      Build Tools: 30.0.3, 33.0.0, 33.0.2
      System Images: android-24 | Google APIs ARM 64 v8a, android-26 | Google APIs ARM 64 v8a, android-29 | Google APIs ARM 64 v8a, android-31 | ARM 64 v8a, android-31 | Google APIs ARM 64 v8a, android-31 | Google Play ARM 64 v8a, android-32 | Google APIs ARM 64 v8a, android-33 | Google APIs ARM 64 v8a, android-33 | Google Play ARM 64 v8a
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: Flamingo 2022.2.1 Patch 2 Flamingo 2022.2.1 Patch 2
    Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
  Languages:
    Java: javac 17 - /Users/bujoralexandru/.jabba/jdk/openjdk@1.17.0/Contents/Home/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.8 => 0.71.8 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Expo Version (if applies)

48.0.18

### Steps to reproduce

I'm not sure how to reproduce, but the things I did were as follows:
1. Connect using Metamask
2. Approve connection
3. Sign a custom message (my apps business logic)
4. Close the app and open it again after some time
5. Voila - the `useWalletConnectModal()` hook says that I am connected and displays my wallet, but when trying to disconnect the session, the mentioned error occurs.

### Snack, code example, screenshot, or link to a repository

```
  const disconnect = useCallback(async () => {
    if (isConnected) {
      return provider
        ?.disconnect()
        .then(() => setInitialSign(false))
        .catch((err) =>
          Alert.alert(
            'Ooops',
            "Something did not work as expected. Please disconnect the session manually, from within the wallet application that you're using, then restart this app."
          )
        );
    }
  }, [isConnected, provider]);
```

**Comment by ignaciosantise** [comment]
hey @bujoralexandru 👋 were you able to reproduce the error? It seems that the session was disconnected on metamask side but the message didn't get to the dapp side. Usually, in those cases if you re-open the app, the session is cleaned successfully. 

How much time did you have the app closed? -> `4. Close the app and open it again after some time`

**Comment by dingcxx** [comment]
> hey @bujoralexandru 👋 were you able to reproduce the error? It seems that the session was disconnected on metamask side but the message didn't get to the dapp side. Usually, in those cases if you re-open the app, the session is cleaned successfully.
> 
> How much time did you have the app closed? -> `4. Close the app and open it again after some time`

I have the same problem too. 

when I call disconnect  will receive error:

{"context": "core"} {"context": "core/expirer"} No matching key. expirer: topic:c9305cc50aae73af4eeb38c6629dd9feaf99f42c5b16f5ab9ad7df3ba215ddf6

it is nonblocking issue , but in this case when I call sign and other write methods jump into metamask didn't show any action view.

my steps

1. connect metamask
2. mint NFT work fine
3. reload app 
4. call mint can jump to metamask and didn't show any action view.
5. jump to my app
6. call disconnect method , receive this error

maybe when init modal will create a new topic?
