### ISSUE TITLE
[bug]: Listener is not working 

### ISSUE THREAD

**Issue by pratul-mindfire** [WalletConnect/modal-react-native#110]
### Description

Listener is not working

### WalletConnect Modal SDK version

"@walletconnect/modal-react-native": "1.1.0",

### Output of `npx react-native info`

System:
  OS: macOS 14.2.1
  CPU: (8) arm64 Apple M1
  Memory: 79.47 MB / 8.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 21.6.0
    path: /opt/homebrew/bin/node
  Yarn:
    version: 1.22.21
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.2.4
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2023.12.04.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.3
    path: /Users/pratuldawande/.gem/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - visionOS 1.0
      - watchOS 10.2
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.1 AI-221.6008.13.2211.9514443
  Xcode:
    version: 15.2/15C500b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 21.0.1
    path: /Library/Java/JavaVirtualMachines/jdk-21.jdk/Contents/Home/bin/javac
  Ruby:
    version: 3.3.0
    path: /opt/homebrew/opt/ruby/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.4
    wanted: 0.72.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: Not found

### Steps to reproduce

Listener is not working . I have tested for metamask and rainbow wallet

### Snack, code example, screenshot, or link to a repository

const {isConnected, provider, open} = useWalletConnectModal();
  const [client, setClient] = useState<Web3Provider>();
  const [modalVisible, setModalVisible] = useState(false);
  const [rpcResponse, setRpcResponse] = useState<any>();
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    // const handleChainChanged = (newChainId: string) => {
    //   console.log(newChainId, 'newChainId')
    // }
    // const handleAccountsChanged = (newAccount: string) => {
    //   console.log(newAccount, 'newAccount')
    // }

    // provider?.events.addListener('chainChanged', handleChainChanged);
    // provider?.events.addListener('accountsChanged', handleAccountsChanged);

    // return () => {
    //   provider?.events.removeAllListeners();
    // }
    provider?.on("chainChanged", (newChain: unknown) => {
      console.log('useEffect::ethereum on "chainChanged"', newChain);
      //setChain(newChain as string);
    });
    provider?.on("connect", () => {
      console.log("connect1234");

    });
    provider?.on("accountsChanged", (_accounts: unknown) => {
      const accounts = _accounts as string[];
      //dispatch(setLogin(!isLogin));
      console.log('useEffect::ethereum on "accountsChanged"', accounts);

    });

  }, [])

**Comment by ignaciosantise** [comment]
Hey @pratul-mindfire 👋 

try setting the listeners when the provider is initialized. Let me know if if works now

```
  useEffect(() => {
    if (provider) {
      provider.on('chainChanged', (newChain: unknown) => {
        console.log('useEffect::ethereum on "chainChanged"', newChain);
      });
      provider.on('connect', () => {
        console.log('connect1234');
      });
      provider.on('accountsChanged', (_accounts: unknown) => {
        const accounts = _accounts as string[];
        console.log('useEffect::ethereum on "accountsChanged"', accounts);
      });
    }
  }, [provider]);
```
