### ISSUE TITLE
[bug]: Error: Socket stalled when trying to connect to wss://relay.walletconnect.com

### ISSUE THREAD

**Issue by yucheng-Li** [WalletConnect/modal-react-native#111]
### Description

        <WalletConnectModal
          projectId={WCPARAMS.PROJECT_ID}
          providerMetadata={WCPARAMS.providerMetadata}
          sessionParams={WCPARAMS.sessionParams}
          relayUrl={'wss://relay.walletconnect.com'}
        />
        

### WalletConnect Modal SDK version

1.1.0

### Output of `npx react-native info`

System:
  OS: macOS 14.5
  CPU: (8) x64 Apple M1
  Memory: 162.25 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.20.1
    path: ~/.asdf/installs/nodejs/18.20.1/bin/node
  Yarn:
    version: 1.22.21
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.5.0
    path: ~/.asdf/plugins/nodejs/shims/npm
  Watchman:
    version: 2024.01.22.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.3
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.5
      - iOS 17.5
      - macOS 14.5
      - tvOS 17.5
      - visionOS 1.2
      - watchOS 10.5
  Android SDK: Not Found
IDEs:
  Android Studio: 2023.1 AI-231.9392.1.2311.11330709
  Xcode:
    version: 15.4/15F31d
    path: /usr/bin/xcodebuild
Languages:
  Java: Not Found
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.6
    wanted: 0.73.6
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: false
  newArchEnabled: false
iOS:
  hermesEnabled: false
  newArchEnabled: false

### Steps to reproduce

        I am in China now, if i not use vpn i will get a error when i in develop. Other way if build to testflight and open the app it will crashes immediately even i use vpn it not work.
        `
 ERROR  {"context": "core"} {"context": "core/relayer"} [Error: Socket stalled when trying to connect to wss://relay.walletconnect.com]
 WARN  {"context": "core"} {"context": "core/relayer"} Connection via wss://relay.walletconnect.com failed, attempting to connect via failover domain wss://relay.walletconnect.org...
 ERROR  {"context": "core"} {"context": "core/relayer"} [Error: WebSocket connection failed for host: wss://relay.walletconnect.org]
 WARN  {"context": "core"} Core Initialization Failure at epoch 1717048281479 [Error: WebSocket connection failed for host: wss://relay.walletconnect.org]
 ERROR  {"context": "core"} WebSocket connection failed for host: wss://relay.walletconnect.org
 INFO  {"context": "client"} SignClient Initialization Failure
`

### Snack, code example, screenshot, or link to a repository

![WechatIMG116](https://github.com/WalletConnect/modal-react-native/assets/61103353/9ba2f959-0583-45c2-9134-4d1506745c1b)

**Comment by ignaciosantise** [comment]
hey @yucheng-Li 👋 can you try removing the `relayUrl={'wss://relay.walletconnect.com'}` prop? Internally we have a fallback logic in case the `.com` fails

also, are you using a VPN? if so, can you turn it off and try again?

**Comment by yucheng-Li** [comment]
已收到

**Comment by ignaciosantise** [comment]
@yucheng-Li any new?

**Comment by yucheng-Li** [comment]
已收到

**Comment by ignaciosantise** [comment]
closing until we have more info
