### ISSUE TITLE
[bug]: 

### ISSUE THREAD

**Issue by bhsrampage** [WalletConnect/modal-react-native#19]
### Description

Under connection to metmask, popup doesnt show the app details for signing and transaction requests. 
It shows
--> metamask.io in dev 
--> uniswap.org in prod versions 

`const providerMetadata = {
  name: 'NFTHodlr',
  description: 'Connect to NFTHodlr App',
  url: 'https://nfthodlr.xyz',
  icons: ['https://ibb.co/XVmwLS3'],
  redirect: {
    native: 'nfthodlr://',
    universal: 'http://app.nfthodlr.xyz/',
  },
};`

**Dev**
![Screenshot_20230630-155039](https://github.com/WalletConnect/modal-react-native/assets/61087568/0043468a-9f67-4322-88ba-05e2f1c80d03)

**Prod** 
![Screenshot_2023-06-30-15-50-15-800_io metamask](https://github.com/WalletConnect/modal-react-native/assets/61087568/cd6ca07c-70a6-419f-bbf8-afe96dd512f5)

### WalletConnect Modal SDK version

1.0.0-rc.3

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
  OS: macOS 13.4.1
  CPU: (8) arm64 Apple M1 Pro
  Memory: 79.69 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.2.0
    path: /opt/homebrew/bin/node
  Yarn:
    version: 1.22.19
    path: /opt/homebrew/bin/yarn
  npm:
    version: 9.6.6
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2023.05.22.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.2 AI-222.4459.24.2221.10121639
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.19
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.0
    wanted: 0.72.0
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

info React Native v0.72.1 is now available (your project is running on v0.72.0).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.72.1
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.72.0
info For more info, check out "https://reactnative.dev/docs/upgrading?os=macos&platform=android".

### Steps to reproduce

Setup walletconnect modal with custom metadata. and sign message or transaction.

### Snack, code example, screenshot, or link to a repository

none

**Comment by ignaciosantise** [comment]
hey @bhsrampage 👋 Each wallet decides how to show the metadata. In case of MetaMask, they show it only in the connection popup:

<img alt="1" height="700" src="https://github.com/WalletConnect/modal-react-native/assets/25931366/38cff225-8f2f-4724-89e7-90b039f0af1a" />

**Comment by bhsrampage** [comment]
With the v1 package i.e react-native-dapp it used to show up properly. In every tx signing popup.
