### ISSUE TITLE
[bug]: {"context": "client"} undefined is not a function.

### ISSUE THREAD

**Issue by NarekAv-Solicy** [WalletConnect/modal-react-native#27]
### Description

I'm getting errors after running the project`
![image](https://github.com/WalletConnect/modal-react-native/assets/115778151/963d2b73-8847-476b-93f7-a431c64d4bbb)

After reloading I don't get errors, but getting one when trying to open the walletconnect modal`
{"context": "client"} undefined is not a function.

Any idea why I can get these errors?

### WalletConnect Modal SDK version

^1.0.0-rc.3

### Output of `npx react-native info`

nfo Fetching system and libraries information...
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i5-10500H CPU @ 2.50GHz
    Memory: 4.94 GB / 15.83 GB
  Binaries:
    Node: 16.19.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.19.3 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: AI-222.4459.24.2221.10121639
    Visual Studio: Not Found
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.8 => 0.71.8
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
info React Native v0.72.1 is now available (your project is running on v0.71.8).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.72.1
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.71.8
info For more info, check out "https://reactnative.dev/docs/upgrading".

### Expo Version (if applies)

^48.0.7

### Steps to reproduce

run the project or open walletConnect modal

### Snack, code example, screenshot, or link to a repository

      import { View, TouchableOpacity, Text } from 'react-native';
      import { SafeAreaView } from 'react-native-safe-area-context';
      import { WalletConnectModal, IProviderMetadata, useWalletConnectModal } from '@walletconnect/modal-react-native';
      import '@walletconnect/react-native-compat';
      import { styles } from './styles';

      const App = (): JSX.Element => {

      const { isConnected, provider, open } = useWalletConnectModal();

      const handleButtonPress = async () => {
          if (isConnected) {
              return provider?.disconnect();
          }
          return open();
       };

       const providerMetadata: IProviderMetadata = {
          name: 'test',
          description: 'test',
          url: 'https://walletconnect.com/',
          icons: ['https://avatars.githubusercontent.com/u/37784886'],
          redirect: {
            native: 'test://',
          },
        };
  
      const sessionParams = {
       namespaces: {
         eip155: {
           methods: [
             'eth_sendTransaction',
             'eth_signTransaction',
             'eth_sign',
             'personal_sign',
             'eth_signTypedData',
           ],
           chains: ['eip155:1'],
           events: ['chainChanged', 'accountsChanged'],
           rpcMap: {},
         },
       },
     };
  

      return (
          <SafeAreaView style={styles.container}>
              <View>
                  <TouchableOpacity onPress={handleButtonPress}>
                      <Text>Connect</Text>
                  </TouchableOpacity>
              </View>
              <WalletConnectModal
                  projectId={'my_id'}
                  providerMetadata={providerMetadata}
                  sessionParams={sessionParams}
              />
          </SafeAreaView>
      );
    };

here is my project [Repo](https://github.com/NarekAv-Solicy/Wallect-connect)

**Comment by DavitK-Solicy** [comment]
Yes am also have this can you pls help

**Comment by NarekAv-Solicy** [comment]
@ignaciosantise can you please take a look here?

**Comment by ignaciosantise** [comment]
hey @NarekAv-Solicy thanks for providing an example repo to reproduce. What u need to do to make it work is move the expo-shim import above `@walletconnect/modal-react-native`

It should look like this:

```
import './expo-crypto-shim';
import { WalletConnectModal, useWalletConnectModal, type IProviderMetadata } from '@walletconnect/modal-react-native';
import { useNetInfo } from '@react-native-community/netinfo';
```

Please confirm it this solves your issue

**Comment by NarekAv-Solicy** [comment]
@ignaciosantise thanks it's solved issue
