### ISSUE TITLE
[bug]: How can i get chainId?

### ISSUE THREAD

**Issue by fatiherdogan01** [WalletConnect/modal-react-native#36]
### Description

Hi,
Firstly why not return chainId from **useWalletConnectModal**?

```
const { provider } = useWalletConnectModal();
...
const chainId = await provider.request({ method: 'eth_chainId' });
console.log({ chainId });
```
I'm trying to get ChainId but it always returns 1.

### WalletConnect Modal SDK version

1.0.0-rc.5

### Output of `npx react-native info`

System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 83.77 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.14.2 - ~/.nvm/versions/node/v18.14.2/bin/node
    Yarn: 1.22.18 - /opt/homebrew/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.14.2/bin/npm
    Watchman: 2023.04.24.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.9971841
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.8 => 0.71.8 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

No response

### Snack, code example, screenshot, or link to a repository

No response

**Comment by ignaciosantise** [comment]
hey @fatiherdogan01 that's the correct way to get the active chain id
if it returns 1, it means the default chain is `eip155:1`

If the session contains more than one chain, you can change it calling `provider?.setDefaultChain('eip155:CHAIN_ID');`

**Comment by fatiherdogan01** [comment]
Yes so, how can I get this network if user is on Polygon Mainnet or X  chain in Wallet (MetaMask v7.3.0)?
```
namespaces: {
    eip155: {
      methods: REQUIRED_METHODS,
      chains: ['eip155:1', 'eip155:137'],
      events: REQUIRED_EVENTS,
      rpcMap: {},
    },
  },
```
If I use these **sessionParams** there is no action in MetaMask.

**Comment by ignaciosantise** [comment]
If you want to switch the chain from metamask, you'll need to so something similar to what's described [here](https://docs.metamask.io/wallet/reference/rpc-api/#example-2)

1. add `wallet_addEthereumChain` and `wallet_switchEthereumChain` to your session params
2. Make the requests using the provider:
```js
try {
  await provider.request({
    method: 'wallet_switchEthereumChain',
    params: [{ chainId: '0xf00' }],
  });
} catch (switchError) {
  // This error code indicates that the chain has not been added to MetaMask.
  if (switchError.code === 4902) {
    try {
      await provider.request({
        method: 'wallet_addEthereumChain',
        params: [
          {
            chainId: '0xf00',
            chainName: '...',
            rpcUrls: ['https://...'] /* ... */,
          },
        ],
      });
    } catch (addError) {
      // handle "add" error
    }
  }
  // handle other "switch" errors
}
```

**Comment by fatiherdogan01** [comment]
I use this. The problem here is that I can't get the current chain after connecting to the wallet.

**Comment by ignaciosantise** [comment]
`provider.request({ method: 'eth_chainId' });` should work.

We currently have this [issue](https://github.com/WalletConnect/modal-react-native/issues/52) with MetaMask in Android, i'll dig into it but in the meantime can you test the same flow with other wallets?
