### ISSUE TITLE
[bug]: no Phantom and cannot connect to Solana from other wallets

### ISSUE THREAD

**Issue by jupiterrosen** [WalletConnect/modal-react-native#41]
### Description

When the modal opens there is no Phantom wallet even though I have added the id to the attribute `explorerRecommendedWalletIds`. 
What's more, in order to switch to Solana, I tried two ways of setting the chain of the provider, the first one is to `provider.setDefaultChain('Solana:mainnetBeta') `
The second is to fill the sessionParams:
```
const  sessionParams = {
  namespaces: {
    solana: {
      methods: [],
      chains: ['solana:mainnetBeta'],
      events: [],
      rpcMap: {},
    },
  },
};
```
However, the first one won't work and for the second one I have tested on Spot wallet and it prompts that the network is unsupported.

### WalletConnect Modal SDK version

 "@walletconnect/modal-react-native": "^1.0.0-rc.6",

### Output of `npx react-native info`

System:
  OS: Windows 10 10.0.22621
  CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700H
  Memory: 2.15 GB / 15.63 GB
Binaries:
  Node:
    version: 16.16.0
    path: C:\Program Files\nodejs\node.EXE
  Yarn:
    version: 1.22.15
    path: C:\Program Files\nodejs\yarn.CMD
  npm:
    version: 8.11.0
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK: Not Found
IDEs:
  Android Studio: AI-212.5712.43.2112.8609683
  Visual Studio: Not Found
Languages:
  Java: 17.0.5
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.3
    wanted: ^0.72.3
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

### Expo Version (if applies)

"expo": "^49.0.0"

### Steps to reproduce

Try to connect with solana network.

### Snack, code example, screenshot, or link to a repository

None

**Comment by glitch-txs** [comment]
Hi, Phantom wallet does not support WalletConnect protocol
