### ISSUE TITLE
[bug]:  request personal_sign receive  error {"code": -32603, "message": "Internal error"}

### ISSUE THREAD

**Issue by dingcxx** [WalletConnect/modal-react-native#43]
### Description

I want sign  message before mint NFT

before sign I need switch chain net to 97, it is success jump to wallet, but jump back at once, and receive error {"code": -32602, "message": "Invalid params"}

and then jump to wallet and sign message , but chain net is not I needed , so I cancel it. after jump to my app, I receive error again {"code": -32603, "message": "Internal error"}

### WalletConnect Modal SDK version

v1.0.0-rc.6

### Output of `npx react-native info`

System:
    OS: macOS 13.4.1
    CPU: (12) arm64 Apple M2 Pro
    Memory: 85.20 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.20.0 - ~/.nvm/versions/node/v16.20.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.24.2 - ~/Documents/workplace/rnsId/rnsIdMobileAPP/node_modules/.bin/npm
    Watchman: 2023.04.10.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /Users/dingc/.rvm/gems/ruby-3.2.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.10121639
    Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
  Languages:
    Java: javac 20 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. walletconnect is already connected.
2.  request  wallet_addEthereumChain switch chain net to 97, current wallet chain net is 280
3. it is success jump to wallet, but jump back my app at once, and receive error {"code": -32602, "message": "Invalid params"}
4. then I request personal_sign jump to wallet success , but chain net is wrong. so I cancel it
5. after jump to my app, I receive error again {"code": -32603, "message": "Internal error"}
6. and long time after receive another error  {"context": "client"}  but no message.

### Snack, code example, screenshot, or link to a repository

<img src="https://github.com/WalletConnect/modal-react-native/assets/117795329/1ed93d6a-0715-4f4b-90ce-b7899928d68d" height="600">
<img src="https://github.com/WalletConnect/modal-react-native/assets/117795329/c239d4cb-6fe3-4c84-bdd7-a53b54e008cc" height="600">
<img src="https://github.com/WalletConnect/modal-react-native/assets/117795329/bc6d78cc-b09c-4fee-9259-4dfd3aa1c9d6" height="600">

**Comment by dingcxx** [comment]
https://github.com/WalletConnect/walletconnect-monorepo/blob/0d9f4f3256daf89c02eb2b4c6b34c7b2637d9415/providers/ethereum-provider/src/EthereumProvider.ts

I read this code, maybe I should change init code .  perhaps you should manage sessionParams by yourself.

**Comment by dingcxx** [comment]
I change my code, but have some wrong below

1. requst wallet_addEthereumChain can jump to wallet 
2.  and added success, also can back to my app.
3.  but not receive request's Promise resolve and reject. 

It is another problem about wallet_addEthereumChain request. I don't know What's the problem?

**Comment by ignaciosantise** [comment]
@dingcxx which wallet are you using to test?

**Comment by ignaciosantise** [comment]
Closing as i cannot reproduce it
