### ISSUE TITLE
[bug]: {"code": -32601, "message": "the method wallet_addEthereumChain does not exist/is not available"}

### ISSUE THREAD

**Issue by ShallowGreen** [WalletConnect/modal-react-native#44]
### Description

```
export const sessionParams = {
  namespaces: {
    eip155: {
      methods: [
        'eth_accounts',
        'eth_requestAccounts',
        'eth_sendRawTransaction',
        'eth_sign',
        'eth_signTransaction',
        'eth_signTypedData',
        'eth_signTypedData_v3',
        'eth_signTypedData_v4',
        'wallet_switchEthereumChain',
        'wallet_addEthereumChain',
        'wallet_getPermissions',
        'wallet_requestPermissions',
        'wallet_registerOnboarding',
        'wallet_watchAsset',
        'wallet_scanQRCode',
        'eth_sendTransaction',
        'personal_sign',
      ],
      chains: ['eip155:1'], //, 'eip155:59140'
      events: ['chainChanged', 'accountsChanged', 'message', 'disconnect', 'connect'],
      rpcMap: {},
    },
  },
};
```

```
 await provider?.request({
        method: 'wallet_addEthereumChain',
        params: [
          {
            chainId: '0x89',
            chainName: 'Polygon Mainnet',
            rpcUrls: ['https://polygon.llamarpc.com'],
          },
        ],
      });

```

{"code": -32601, "message": "the method wallet_addEthereumChain does not exist/is not available"}

```
import { createWalletClient, custom, http, createPublicClient } from 'viem';

const client = createWalletClient({
        transport: custom(provider as any),
      });

```

```
 await client?.addChain({ chain });

// or

 await client?.switchChain(chain);
```
Details: the method wallet_addEthereumChain does not exist/is not available
Version: viem@1.2.15]

Details: the method wallet_switchEthereumChain does not exist/is not available
Version: viem@1.2.15]

### WalletConnect Modal SDK version

1.0.0-rc.6

### Output of `npx react-native info`

System:
  OS: macOS 12.6
  CPU: (10) x64 Apple M1 Pro
  Memory: 33.29 MB / 16.00 GB
  Shell:
    version: 5.8.1
    path: /bin/zsh
Binaries:
  Node:
    version: 18.12.1
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.19
    path: /usr/local/bin/yarn
  npm:
    version: 8.19.2
    path: /usr/local/bin/npm
  Watchman:
    version: 2023.06.26.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.11.3
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.2
      - iOS 16.2
      - macOS 13.1
      - tvOS 16.1
      - watchOS 9.1
  Android SDK:
    API Levels:
      - "28"
      - "29"
      - "30"
      - "31"
      - "32"
      - "33"
    Build Tools:
      - 28.0.3
      - 29.0.2
      - 30.0.2
      - 30.0.3
      - 31.0.0
      - 32.0.0
      - 33.0.0
      - 34.0.0
    System Images:
      - android-33 | Google APIs ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2022.1 AI-221.6008.13.2211.9514443
  Xcode:
    version: 14.2/14C18
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 19.0.2
    path: /usr/bin/javac
  Ruby:
    version: 3.2.2
    path: /opt/homebrew/opt/ruby/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.0
    wanted: 0.72.0
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

### Steps to reproduce

Try to add chain and switch chain

### Snack, code example, screenshot, or link to a repository

none

**Comment by dingcxx** [comment]
maybe you should  read [EthereumProvider](https://github.com/WalletConnect/walletconnect-monorepo/blob/0d9f4f3256daf89c02eb2b4c6b34c7b2637d9415/providers/ethereum-provider/src/EthereumProvider.ts) code. in some wallet not support your method list, ex: rainbow, you should put methods to optionalNamespaces.eip155.methods, as same as chains

**Comment by ignaciosantise** [comment]
hey @ShallowGreen this is a wallet issue. Which wallet are you using?
If you are using Trust Wallet you need to add all the chains in the session to be able to call `wallet_switchEthereumChain`

Something like this:
```js
export const sessionParams = {
  namespaces: {
    eip155: {
      methods: [
        'eth_sendTransaction',
        'eth_signTransaction',
        'eth_sign',
        'personal_sign',
        'eth_signTypedData',
        'wallet_addEthereumChain',
        'wallet_switchEthereumChain',
      ],
      chains: ['eip155:1'],
      events: ['chainChanged', 'accountsChanged'],
      rpcMap: {},
    },
  },
  optionalNamespaces: {
    eip155: {
      methods: [
        'eth_sendTransaction',
        'eth_signTransaction',
        'eth_sign',
        'personal_sign',
        'eth_signTypedData',
        'wallet_addEthereumChain',
        'wallet_switchEthereumChain',
      ],
      chains: ['eip155:137'],
      events: ['chainChanged', 'accountsChanged'],
      rpcMap: {},
    },
  },
};
```

**Comment by saber-yy** [comment]
export const sessionParams = {
  namespaces: {
    eip155: {
      methods: [
        'eth_sendTransaction',
        'eth_signTransaction',
        'eth_sign',
        'personal_sign',
        'eth_signTypedData',
        'wallet_addEthereumChain',
        'wallet_switchEthereumChain',
      ],
      chains: ['eip155:1'],
      events: ['chainChanged', 'accountsChanged', 'connect', 'disconnect'],
      rpcMap: {},
    },
  },
  optionalNamespaces: {
    eip155: {
      methods: [
        'eth_sendTransaction',
        'eth_signTransaction',
        'eth_sign',
        'personal_sign',
        'eth_signTypedData',
        'wallet_addEthereumChain',
        'wallet_switchEthereumChain',
      ],
      chains: [
        'eip155:3',
        'eip155:4',
        'eip155:25',
        'eip155:56',
        'eip155:66',
        'eip155:97',
        'eip155:137',
        'eip155:42161',
        'eip155:43114',
        'eip155:128',
      ],
      events: ['chainChanged', 'accountsChanged', 'connect', 'disconnect'],
      rpcMap: {},
    },
  },
}

I tried this code ,and still get this error , was using Metamask .

**Comment by saber-yy** [comment]
`export const sessionParams = {
  namespaces: {
    eip155: {
      methods: [
        'eth_sendTransaction',
        'eth_signTransaction',
        'eth_sign',
        'personal_sign',
        'eth_signTypedData',
        'wallet_addEthereumChain',
        'wallet_switchEthereumChain',
      ],
      chains: ['eip155:1'],
      events: ['chainChanged', 'accountsChanged', 'connect', 'disconnect'],
      rpcMap: {},
    },
  },
  optionalNamespaces: {
    eip155: {
      methods: [
        'eth_sendTransaction',
        'eth_signTransaction',
        'eth_sign',
        'personal_sign',
        'eth_signTypedData',
        'wallet_addEthereumChain',
        'wallet_switchEthereumChain',
      ],
      chains: [
        'eip155:3',
        'eip155:4',
        'eip155:25',
        'eip155:56',
        'eip155:66',
        'eip155:97',
        'eip155:137',
        'eip155:42161',
        'eip155:43114',
        'eip155:128',
      ],
      events: ['chainChanged', 'accountsChanged', 'connect', 'disconnect'],
      rpcMap: {},
    },
  },
};
`
I tried this code ,and still get this error , was using Metamask .

when call wallet_switchEthereumChain method

`{"method":"wallet_switchEthereumChain","params":[{"chainId":"0x38"}]}`

 there throw a error : [TypeError: I.startsWith is not a function. (In 'I.startsWith("0x")', 'I.startsWith' is undefined)].

when call wallet_addEthereumChain method 

`{"method":"wallet_addEthereumChain","params":[{"chainId":"0x61","chainName":"Bsc Testnet","nativeCurrency":{"name":"TBNB","symbol":"TBNB","decimals":18},"rpcUrls":["https://data-seed-prebsc-1-s1.binance.org:8545/"],"blockExplorerUrls":["https://testnet.bscscan.com"]}]}
`

there throw a error :{"code": -32601, "message": "the method wallet_addEthereumChain does not exist/is not available"}

**Comment by ignaciosantise** [comment]
@saber-yy i couldn't reproduce the issue in MetaMask, can you upload an example project with the reproducible issue?
Here's what i tried and it worked:

1. SessionParams:

```
export const sessionParams = {
  namespaces: {
    eip155: {
      methods: [
        'eth_sendTransaction',
        'eth_signTransaction',
        'eth_sign',
        'personal_sign',
        'eth_signTypedData',
        'wallet_addEthereumChain',
        'wallet_switchEthereumChain',
      ],
      chains: ['eip155:1'],
      events: ['chainChanged', 'accountsChanged', 'connect', 'disconnect'],
      rpcMap: {},
    },
  },
};

```

2. Method to switch/add chain:
```
  const switchChain = async () => {
    try {
      await provider?.request({
        method: 'wallet_switchEthereumChain',
        params: [
          {
            chainId: '0x38',
          },
        ],
      });
    } catch (error) {
      await provider?.request({
        method: 'wallet_addEthereumChain',
        params: [
          {
            chainId: '0x38',
            chainName: 'Bsc',
            nativeCurrency: { name: 'BNB', symbol: 'BNB', decimals: 18 },
            rpcUrls: ['https://bsc.publicnode.com'],
          },
        ],
      });
    }
  };
```

**Comment by NarekAv-Solicy** [comment]
```typescript
export const sessionParams = {
    namespaces: {
      eip155: {
        methods: [
          'eth_sendTransaction',
          'eth_signTransaction',
          'eth_sign',
          'personal_sign',
          'eth_signTypedData',
          'wallet_addEthereumChain',
          'wallet_switchEthereumChain',
        ],
        chains: ['eip155:1', 'eip155:137', 'eip155:5'],
        events: ['chainChanged', 'accountsChanged'],
        rpcMap: {},
      },
    },
    optionalNamespaces: {
        eip155: {
          methods: [
            'eth_sendTransaction',
            'eth_signTransaction',
            'eth_sign',
            'personal_sign',
            'eth_signTypedData',
            'wallet_addEthereumChain',
            'wallet_switchEthereumChain',
          ],
          chains: ['eip155:1', 'eip155:137', 'eip155:5'],
          events: ['chainChanged', 'accountsChanged'],
          rpcMap: {},
        },
      },
  };

const switchChain = async chainId => {
        try {
            await provider?.request({
                method: 'wallet_switchEthereumChain',
                params: [
                    {
                        chainId: `0x${chainId.toString(16)}`
                    }
                ]
            });
        } catch (error) {
            console.log(error);
        }
    };
``` 
getting `[Error: Failed to switch to chain 'eip155:5'. The chain is not approved or the wallet does not support 'wallet_switchEthereumChain' method.]`

if I'm using `wallet_addEthereumChain` method, getting  
{
  "code": -32601,
  "message": "The method wallet_addEthereumChain does not exist/is not available",
}


I'm using trust wallet

@ignaciosantise can you take a look here?

**Comment by mertcankose** [comment]
> ```ts
> export const sessionParams = {
>     namespaces: {
>       eip155: {
>         methods: [
>           'eth_sendTransaction',
>           'eth_signTransaction',
>           'eth_sign',
>           'personal_sign',
>           'eth_signTypedData',
>           'wallet_addEthereumChain',
>           'wallet_switchEthereumChain',
>         ],
>         chains: ['eip155:1', 'eip155:137', 'eip155:5'],
>         events: ['chainChanged', 'accountsChanged'],
>         rpcMap: {},
>       },
>     },
>     optionalNamespaces: {
>         eip155: {
>           methods: [
>             'eth_sendTransaction',
>             'eth_signTransaction',
>             'eth_sign',
>             'personal_sign',
>             'eth_signTypedData',
>             'wallet_addEthereumChain',
>             'wallet_switchEthereumChain',
>           ],
>           chains: ['eip155:1', 'eip155:137', 'eip155:5'],
>           events: ['chainChanged', 'accountsChanged'],
>           rpcMap: {},
>         },
>       },
>   };
> 
> const switchChain = async chainId => {
>         try {
>             await provider?.request({
>                 method: 'wallet_switchEthereumChain',
>                 params: [
>                     {
>                         chainId: `0x${chainId.toString(16)}`
>                     }
>                 ]
>             });
>         } catch (error) {
>             console.log(error);
>         }
>     };
> ```
> 
> getting `[Error: Failed to switch to chain 'eip155:5'. The chain is not approved or the wallet does not support 'wallet_switchEthereumChain' method.]`
> 
> if I'm using `wallet_addEthereumChain` method, getting `{ "code": -32601, "message": "The method wallet_addEthereumChain does not exist/is not available", }`
> 
> I'm using trust wallet
> 
> @ignaciosantise can you take a look here?

Same issue

**Comment by glitch-txs** [comment]
@NarekAv-Solicy @mertcankose chain 5 is Goerli, most mobile wallets do not support testnets.
