### ISSUE TITLE
[bug]: Metamask | Multichain system is not supported

### ISSUE THREAD

**Issue by boulinb** [WalletConnect/modal-react-native#6]
### Description

Hi everyone!

Here is what I noticed with the Metamask update: When I try to connect with Metamask on one chain, everything works perfectly well, but if I configure several chains nothing happens (no connection requests).

For example, this code snippet works perfectly: 

```
const sessionParams = {
    namespaces: {
      eip155: {
        methods: REQUIRED_METHODS,
        chains: ['eip155:1'],
        events: REQUIRED_EVENTS,
        rpcMap: {},
      },
    }
  };
```

On the other hand, if several chains are configured, the information is not processed by WalletConnect, which has no errors on its side, and Metamask, which displays no errors:

```
const sessionParams = {
    namespaces: {
      eip155: {
        methods: REQUIRED_METHODS,
        chains: ['eip155:1', 'eip155:56', 'eip155:137'],
        events: REQUIRED_EVENTS,
        rpcMap: {},
      },
    }
  };
```

After some research I realised that I could transfer chains other than (BNB & Polygon) as optional, which partially solves the problem since Metamask will only receive one chain and will propose the connection:

```
const sessionParams = {
    namespaces: {
        eip155: {
            methods: REQUIRED_METHODS,
            chains: ['eip155:1'],
            events: REQUIRED_EVENTS,
            rpcMap: {},
        },
    },
    optionalNamespaces: {
        eip155: {
            methods: REQUIRED_METHODS,
            chains: ['eip155:56', 'eip155:137'],
            events: REQUIRED_EVENTS,
            rpcMap: {},
        },
    }
};
```

But this approach with the optional namespace opens up new problems: 

- Rainbow ignores optional chains and proposes a connection only to the configured namespace
- When the user wants to make a request on a chain other than the one defined, WalletConnect will return an error informing us that the chain is not configured (Metamask, Rainbow and all other wallets that ignore optionalNamespaces).

If people have the same problem, I'd love to hear your opinion! 😄

### WalletConnect Modal SDK version

1.0.0-rc.2

### Output of `npx react-native info`

System:
    OS: macOS 13.3.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 499.93 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.10.0 - ~/.nvm/versions/node/v16.10.0/bin/node
    Yarn: 1.22.19 - ~/Documents/Projects/nefting-front/node_modules/.bin/yarn
    npm: 7.24.0 - ~/.nvm/versions/node/v16.10.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.8 => 0.71.8 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Expo Version (if applies)

48.0.17

### Steps to reproduce

Details in description.

### Snack, code example, screenshot, or link to a repository

https://github.com/boulinb/web3modal-react-native-issue

**Comment by bhsrampage** [comment]
I kind of solved it by keeping the chains array empty. My flow is that I connect the wallet on any chain and then request to switch it to the desired chain. 

This happens only during the first connection. If the user switches the chain in the wallet once again and opens the dapp on the connected state I am unable to send the request to switch as walletconnect is not recognizing the current set chain in the wallet. (If anyone is able to do it then please comment below)

**Comment by dingcxx** [comment]
same problem

maybe you can maintain a suite of  connector,  just like wagmi

**Comment by mohandesjiri** [comment]
Any update on this?

**Comment by ignaciosantise** [comment]
Hey, MM doesn't support multichain that way, in order to make it work in MM, you have to add each new chain calling `wallet_addEthereumChain`.

The sessionParam should have only one chain, and they don't support optionalNamespaces.

Here's a piece of code you can use:

1. Session params:
```
export const sessionParams = {
  namespaces: {
    eip155: {
      methods: [
        'eth_sendTransaction',
        'eth_signTransaction',
        'eth_sign',
        'personal_sign',
        'eth_signTypedData',
        'wallet_addEthereumChain',
        'wallet_switchEthereumChain',
      ],
      chains: ['eip155:1'],
      events: ['chainChanged', 'accountsChanged', 'connect', 'disconnect'],
      rpcMap: {},
    },
  },
};
```

2. Method to switch/add chain:
```
  const switchChain = async () => {
    try {
      await provider?.request({
        method: 'wallet_switchEthereumChain',
        params: [
          {
            chainId: '0x38',
          },
        ],
      });
    } catch (error) {
      await provider?.request({
        method: 'wallet_addEthereumChain',
        params: [
          {
            chainId: '0x38',
            chainName: 'Bsc',
            nativeCurrency: { name: 'BNB', symbol: 'BNB', decimals: 18 },
            rpcUrls: ['https://bsc.publicnode.com'],
          },
        ],
      });
    }
  };
```

Also, beware of this: https://github.com/WalletConnect/modal-react-native/issues/52#issuecomment-1660905855
In Android, the `chainEvent` is not sent correctly from MM

We'll have to wait until wallets implement optionalNamespaces correctly.

Im closing this, as there's no possible action from our side
