### ISSUE TITLE
[bug]: Module not found: Error: Can't resolve 'react-native'

### ISSUE THREAD

**Issue by na-bio** [WalletConnect/modal-react-native#63]
### Description

Project is failing when I try to build it:
`Module not found: Error: Can't resolve 'react-native' in '.../node_modules/@walletconnect/modal-react-native/lib/module/config'`

Link to the code I was working with, its just following the [demo](https://docs.walletconnect.com/2.0/reactnative/walletconnectmodal/dapp-usage) tutorial:
[https://github.com/na-bio/web3-modal-demo](https://github.com/na-bio/web3-modal-demo
)

There was a similar bug reported for the mono-repo prior: https://github.com/WalletConnect/walletconnect-monorepo/issues/2361

### WalletConnect Modal SDK version

1.0.0-rc.7

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
  OS: macOS 13.4.1
  CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Memory: 619.83 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.17.0
    path: ~/.nvm/versions/node/v18.17.0/bin/node
  Yarn:
    version: 1.22.19
    path: /usr/local/bin/yarn
  npm:
    version: 9.6.7
    path: ~/.nvm/versions/node/v18.17.0/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods: Not Found
SDKs:
  iOS SDK: Not Found
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
  Xcode:
    version: /undefined
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.15
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: ^18.2.0
  react-native:
    installed: 0.72.3
    wanted: ^0.72.3
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

### Steps to reproduce

Download and build the code link. Or start from demo link.

### Snack, code example, screenshot, or link to a repository

https://github.com/na-bio/web3-modal-demo

**Comment by ignaciosantise** [comment]
hey @na-bio for web projects you have to use our Web SDK. You can read the docs here: https://docs.walletconnect.com/2.0/web/web3modal/react/wagmi/installation
