### ISSUE TITLE
[feature] Expose `resetApp` function on `useWalletConnectModal`

### ISSUE THREAD

**Issue by iacopo87** [WalletConnect/modal-react-native#65]
### What problem does this new feature solve?

Hello,
I'd like to be able to show the `WalletConnectModal` in its initial state, ignoring the current session state. 

### Describe the solution you'd like

To do that I'd like to have exposed `resetApp` on `useWalletConnectModal`.

thanks,
Iacopo

**Comment by ignaciosantise** [comment]
hey @iacopo87 what's the use case for this feature? `resetApp` is called after a successful disconection from the wallet

**Comment by iacopo87** [comment]
ok, thanks. So it's not needed
