### ISSUE TITLE
[bug]: `explorerExcludedWalletIds` excludes all

### ISSUE THREAD

**Issue by sasicodes** [WalletConnect/modal-react-native#68]
### Description

using `explorerExcludedWalletIds`using initialization excludes all wallets including `explorerRecommendedWalletIds`.

Experiencing this recently, before it was good, showed only `explorerRecommendedWalletIds` in both main modal and view all view.

### WalletConnect Modal SDK version

1.0.0-rc.7

### Output of `npx react-native info`

im using expo

### Expo Version (if applies)

48.0.18

### Steps to reproduce

```
<WalletConnectModal
            themeMode="dark"
            projectId={WC_PROJECT_ID}
            explorerExcludedWalletIds="ALL"
            providerMetadata={providerMetadata}
            explorerRecommendedWalletIds={explorerRecommendedWalletIds}
          />
```

### Snack, code example, screenshot, or link to a repository

<img width="442" alt="2023-08-05 at 21 40 56@2x" src="https://github.com/WalletConnect/modal-react-native/assets/29498872/59a8af8e-0e52-4383-a171-cc491149484f">
<img width="452" alt="2023-08-05 at 21 41 10@2x" src="https://github.com/WalletConnect/modal-react-native/assets/29498872/08c2a9a2-23d3-414e-8e9a-9497fd21a232">

**Comment by sasicodes** [comment]
If I removed `explorerExcludedWalletIds` works, but i dont want ALL wallets in view all modal.

```
<WalletConnectModal
            themeMode="dark"
            projectId={WC_PROJECT_ID}
            // explorerExcludedWalletIds="ALL"
            providerMetadata={providerMetadata}
            explorerRecommendedWalletIds={explorerRecommendedWalletIds}
          />
```
<img width="456" alt="2023-08-05 at 21 42 44@2x" src="https://github.com/WalletConnect/modal-react-native/assets/29498872/b1f2b382-b8bf-4f2f-82c2-bc8d85fb3af6">
<img width="453" alt="2023-08-05 at 21 43 12@2x" src="https://github.com/WalletConnect/modal-react-native/assets/29498872/f3ccb4db-93c5-4c57-a27d-df226366701c">

**Comment by ignaciosantise** [comment]
@sasicodes thanks for reaching out!

You are right, I broke some cases in the latest release 🥲 

I already created a PR to solve that, once it's merged i'll release a canary version for you to test it 💪

**Comment by ignaciosantise** [comment]
@sasicodes `@walletconnect/modal-react-native@1.0.0-rc.10` released 🎉  Can you check if it works with your case?

**Comment by sasicodes** [comment]
> @sasicodes `@walletconnect/modal-react-native@1.0.0-rc.10` released 🎉 Can you check if it works with your case?

yes, now `explorerExcludedWalletIds="ALL"` is working fine. Only defined wallet are shown 👍🏻 

Thanks.
