### ISSUE TITLE
[feature] please add the logger parameter to the options

### ISSUE THREAD

**Issue by fatiherdogan01** [WalletConnect/modal-react-native#69]
### What problem does this new feature solve?

I don't want see logs in development.

### Describe the solution you'd like

Add the logger parameter to the options.

**Comment by ignaciosantise** [comment]
Hey @fatiherdogan01 👋 we won't add this feature yet.

If you need to turn em off, you can patch this code: https://github.com/WalletConnect/modal-react-native/blob/6f945d87f55801911980a88b72e0a70f5fefc7ae/src/utils/ProviderUtil.ts#L14
