### ISSUE TITLE
[bug]: Connection Modal doesn't show in the metamask when click metamask in the web3modal

### ISSUE THREAD

**Issue by DailaYoffey** [WalletConnect/modal-react-native#7]
### Description

-click the metamask in the react native modal

![image](https://github.com/WalletConnect/modal-react-native/assets/136822190/48720678-19a6-4dff-b162-084dd58c78f0)

-doesn't show connection modal in the metamask

![image](https://github.com/WalletConnect/modal-react-native/assets/136822190/fb8c4626-2724-4af1-ad76-8766f780166b)

-expo log

![image](https://github.com/WalletConnect/modal-react-native/assets/136822190/8c6a5e19-1b42-4db3-a971-41407b2a8210)

### WalletConnect Modal SDK version

2.0

### Output of `npx react-native info`

No error

### Expo Version (if applies)

48.0.0

### Steps to reproduce

click the metamask icon in the react native web3 modal

### Snack, code example, screenshot, or link to a repository

![image](https://github.com/WalletConnect/modal-react-native/assets/136822190/1a55051a-4425-409e-9170-82d64741c163)

![image](https://github.com/WalletConnect/modal-react-native/assets/136822190/8f94a628-8761-4e50-8ea2-95234fcd8e1e)

**Comment by DailaYoffey** [comment]
How can I fix this?

**Comment by dingcxx** [comment]
I meet the same issue

platform: iOS

MetaMask version:  v6.3.0(1095)

**Comment by m1heng** [comment]
you need to update your Metamask to v7.0.1

**Comment by dingcxx** [comment]
> you need to update your Metamask to v7.0.1

ok , let me try it , it just updated two days ago in my market.

**Comment by ignaciosantise** [comment]
@DailaYoffey are you using MetaMask v7.0?
