### ISSUE TITLE
[bug]: Network change not propagated

### ISSUE THREAD

**Issue by Badra00** [WalletConnect/modal-react-native#87]
### Description

Hello 
After a change of network on metamask, if we change the network after connection. 
Using the provider to retrieve the network, we still have the first one.

### WalletConnect Modal SDK version

1.0.0-rc.11

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
  OS: macOS 13.0
  CPU: (10) arm64 Apple M2 Pro
  Memory: 87.45 MB / 32.00 GB
  Shell:
    version: 5.8.1
    path: /bin/zsh
Binaries:
  Node:
    version: 18.13.0
    path: ~/.nvm/versions/node/v18.13.0/bin/node
  Yarn:
    version: 1.22.19
    path: ~/.nvm/versions/node/v18.13.0/bin/yarn
  npm:
    version: 8.19.3
    path: ~/.nvm/versions/node/v18.13.0/bin/npm
  Watchman:
    version: 2023.01.30.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /Users/badra/.rvm/gems/ruby-3.0.5/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK: Not Found
IDEs:
  Android Studio: Electric Eel 2022.1.1 Patch 1 Electric Eel 2022.1.1 Patch 1
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.18
    path: /usr/bin/javac
  Ruby:
    version: 3.0.5
    path: /Users/badra/.rvm/rubies/ruby-3.0.5/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.3
    wanted: 0.72.3
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: false
  newArchEnabled: false

### Steps to reproduce

- Launch the app
- Connect to a wallet using metamask
- click on get network
- change network
- go back to the app
- click on get network

### Snack, code example, screenshot, or link to a repository

https://github.com/Badra00/TestWalletConnect

**Comment by mertcankose** [comment]
same

**Comment by glitch-txs** [comment]
This was an issue on MetaMask side and should be fixed in the last version, closing for now, I'd suggest opening an issue in the MetaMask repository if still persists, if you find this issue in multiple wallets feel free to reopen it. Thanks!
