### ISSUE TITLE
Internal Error : {"code": -32603, "message": "Internal error"}

### ISSUE THREAD

**Issue by jobinabraham** [WalletConnect/modal-react-native#9]
### Description

Hey Community...Trying to migrate v1 react-native dapp  implementation to v2 in my react-native application. When trying to migrate "sendTransation" call from V1 to "provider.request" in V2, getting JSON-RPC error from metamask. The v1 version is working correctly so I am assuming its not an issue with metamask. No params have changed just the function. Please help me out. 
```
import {
  WalletConnectModal,
  useWalletConnectModal,
} from '@walletconnect/modal-react-native';
 const connector = useWalletConnectModal();

//----------V1 Version start--------------------//
connector.sendTransaction({
          data: encodedData,
          from: account,
          to: tokenAddress,
          nonce,
          maxFee: 1573479400382,
          maxPriorityFee: 115446958670,
        })
//----------V1 Version End--------------------//

//----------V2 Version Start------------------//
 connector?.provider
        ?.request({
          method: 'eth_sendTransaction',
          params: [{
            data: encodedData,
            from: account,
            to: tokenAddress,
            nonce,
            maxFee: 1573479400382,
            maxPriorityFee: 115446958670,
          },
          ],
        })
//----------V2 Version End--------------------//
```
Error from Metamask: {"code": -32603, "message": "Internal error"}

### WalletConnect Modal SDK version

1.0.0-rc.2

### Output of `npx react-native info`

System:
    OS: Linux 6.2 Pop!_OS 22.04 LTS
    CPU: (8) x64 AMD Ryzen 5 2400G with Radeon Vega Graphics
    Memory: 1.72 GB / 13.58 GB
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 18.14.2 - ~/.nvm/versions/node/v18.14.2/bin/node
    Yarn: Not Found
    npm: 9.6.2 - ~/Developer/professional/wakanda/node_modules/.bin/npm
    Watchman: 4.9.0 - /usr/bin/watchman
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 11.0.18 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.4 => 0.71.4 
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

```
import {
  WalletConnectModal,
  useWalletConnectModal,
} from '@walletconnect/modal-react-native';
 const connector = useWalletConnectModal();

//----------V1 Version start--------------------//
connector.sendTransaction({
          data: encodedData,
          from: account,
          to: tokenAddress,
          nonce,
          maxFee: 1573479400382,
          maxPriorityFee: 115446958670,
        })
//----------V1 Version End--------------------//

//----------V2 Version Start------------------//
 connector?.provider
        ?.request({
          method: 'eth_sendTransaction',
          params: [{
            data: encodedData,
            from: account,
            to: tokenAddress,
            nonce,
            maxFee: 1573479400382,
            maxPriorityFee: 115446958670,
          },
          ],
        })
//----------V2 Version End--------------------//
```

Error from Metamask: {"code": -32603, "message": "Internal error"}

### Snack, code example, screenshot, or link to a repository

<img height="700" alt="Screenshot_20230626-190946_MetaMask" src="https://github.com/WalletConnect/modal-react-native/assets/9764162/e83ce74f-c17f-4696-a110-6a2e105850d2">

<img height="700" alt="Screenshot_20230626-190959_MetaMask" src="https://github.com/WalletConnect/modal-react-native/assets/9764162/7cd5dccd-93b2-4a1b-aa0e-e00a0d9723cc">

**Comment by ignaciosantise** [comment]
hey @jobinabraham 👋  can you confirm you are using MetaMask v7.0.1? Also, can you upload the `encodedData` used in the example?

**Comment by jobinabraham** [comment]
@ignaciosantise 

`Result of running Contract?.interface?.parseTransaction on th encoded data:
{"args": ["0x812806cd4ec74333425b864A5EA71Bf0217b3FD5", [Object]], "functionFragment": {"_isFragment": true, "constant": false, "constructor": [Function FunctionFragment], "format": [Function anonymous], "gas": null, "inputs": [[ParamType], [ParamType]], "name": "transfer", "outputs": [[ParamType]], "payable": false, "stateMutability": "nonpayable", "type": "function"}, "name": "transfer", "sighash": "0xa9059cbb", "signature": "transfer(address,uint256)", "value": {"hex": "0x00", "type": "BigNumber"}}
`

`Result of running  Contract.interface.decodeFunctionData(transferFragment, encodedData) :
["0x812806cd4ec74333425b864A5EA71Bf0217b3FD5", {"hex": "0x016345785d8a0000", "type": "BigNumber"}]
`

**Comment by ignaciosantise** [comment]
@jobinabraham does it only happen with Polygon testnet?
I've just tried this in Goerli Network and it works:

```
  const send = async () => {
    if (isConnected) {
      const transaction = {
        from: '0x...',
        to: '0x...',
        value: sanitizeHex(numberToHex(0)),
        data: '0x',
      };
      const response = await provider?.request({
        method: 'eth_sendTransaction',
        params: [transaction],
      });
    }
  };
```

**Comment by daniiba** [comment]
Getting the same error when using metamask and calling this
`const typedSignature = await web3Provider.send('eth_signTypedData', [address, JSON.stringify(typedData)]);`

**Comment by jobinabraham** [comment]
> @jobinabraham does it only happen with Polygon testnet? I've just tried this in Goerli Network and it works:
> 
> ```
>   const send = async () => {
>     if (isConnected) {
>       const transaction = {
>         from: '0x...',
>         to: '0x...',
>         value: sanitizeHex(numberToHex(0)),
>         data: '0x',
>       };
>       const response = await provider?.request({
>         method: 'eth_sendTransaction',
>         params: [transaction],
>       });
>     }
>   };
> ```

@ignaciosantise I guess yes. Polygon Mainnet seems to be working fine, although it doesn't seem to respect the maxFee params passed

**Comment by ignaciosantise** [comment]
@jobinabraham It seems to be an issue with MetaMask. I see you opened an issue on their repo, let's wait for their response there -> https://github.com/MetaMask/metamask-mobile/issues/6715

I modified a little bit your first message/images size to make it more clear, it would be good if you change it in MM post too 💪
